### ISSUE TITLE
Preseed setting `mirror/http/proxy` is not set correctly when using environment variables for `build-image.sh`.

### ISSUE THREAD

**Issue by Atlas974** [ILLGrenoble/visa-image-template-example#2]
When using the script `build-image.sh` without any options but with environment variables, the preseed setting `mirror/http/proxy` is not set correctly causing the build of the `system-base` image to fail (the Ubuntu archive mirror can't be reached).

When the option `--http-proxy <URL>` is used to set the HTTP proxy URL, the script sets the variable `PACKER_HTTP_PROXY` (`build-image.sh:32:     PACKER_HTTP_PROXY="$2"`); whereas when using the `VISA_HTTP_PROXY` environment variable, PACKER_HTTP_PROXY is set to `"\"\""` (`build-image.sh:15:PACKER_HTTP_PROXY="\"\""`).

The variable `PACKER_HTTP_PROXY` is then used to define the `{http_proxy}` setting in the file `templates/system-base/environment.yml.tlt` (`build-image.sh:66:sed -e "s|{http_proxy}|$PACKER_HTTP_PROXY|g" -e "s|{no_proxy}|$PACKER_NO_PROXY_HOSTS|g"  templates/system-base/environment.yml.tlt > templates/system-base/environment.yml`) :
```
environment:
  proxy: {http_proxy}
  no_proxy: {no_proxy}
  cpus: 1
  memory: 4096
  disk_size: 10000
  ubuntu_mirror: http://archive.ubuntu.com/ubuntu/dists
  ubuntu_codename: bionic
  ubuntu_docker_image: ubuntu:18.04
  preseed_file_name: preseed-system-base.cfg
  ssh_username: root
templates/system-base/environment.yml.tlt (END)
```

The `proxy` environment variable then defines the preseed setting `mirror/http/proxy` : `templates/system-base/manifest.yml:33:        - "mirror/http/proxy={{ proxy }} "`

I don't know if this is the expected behavior, but I think it might be worthwhile to specify in the documentation that using the `VISA_HTTP_PROXY` and `VISA_NO_PROXY_HOSTS` environment variables does not completely replace the `--http-proxy <URL>` and `--no-proxy <no proxy hosts>` options in the `build-image.sh` script.
